export const countryCodes = {
  A1: 'Qatar',
  A2: 'Ecuador',
  A3: 'Senegal',
  A4: 'Netherlands',

  B1: 'England',
  B2: 'Iran',
  B3: 'USA',
  B4: 'Wales',

  C1: 'Argentina',
  C2: 'Saudi Arabia',
  C3: 'Mexico',
  C4: 'Poland',

  D1: 'France',
  D2: 'Australia',
  D3: 'Denmark',
  D4: 'Tunisia',

  E1: 'Spain',
  E2: 'Costa Rica',
  E3: 'Germany',
  E4: 'Japan',

  F1: 'Belgium',
  F2: 'Canada',
  F3: 'Morocco',
  F4: 'Croatia',

  G1: 'Brazil',
  G2: 'Serbia',
  G3: 'Switzerland',
  G4: 'Cameroon',

  H1: 'Portugal',
  H2: 'Ghana',
  H3: 'Uruguay',
  H4: 'South Korea',

  TIE: 'TIE',
}
export const countryCodesShort = {
  A1: 'QAT',
  A1Flag: 'QAT',
  A2: 'ECU',
  A2Flag: 'ECU',
  A3: 'SEN',
  A3Flag: 'SEN',
  A4: 'NED',
  A4Flag: 'NED',

  B1: 'ENG',
  B1Flag: 'ENG',
  B2: 'IRN',
  B2Flag: 'IRN',
  B3: 'USA',
  B3Flag: 'USA',
  B4: 'WAL',
  B4Flag: 'WAL',

  C1: 'ARG',
  C1Flag: 'ARG',
  C2: 'KSA',
  C2Flag: 'KSA',
  C3: 'MEX',
  C3Flag: 'MEX',
  C4: 'POL',
  C4Flag: 'POL',

  D1: 'FRA',
  D1Flag: 'FRA',
  D2: 'AUS',
  D2Flag: 'AUS',
  D3: 'DEN',
  D3Flag: 'DEN',
  D4: 'TUN',
  D4Flag: 'TUN',

  E1: 'ESP',
  E1Flag: 'ESP',
  E2: 'CRC',
  E2Flag: 'CRC',
  E3: 'GER',
  E3Flag: 'https://media.api-sports.io/football/teams/25.png',
  E4: 'JPN',
  E4Flag: 'https://media.api-sports.io/football/teams/12.png',

  F1: 'BEL',
  F1Flag: 'https://media.api-sports.io/football/teams/1.png',
  F2: 'CAN',
  F2Flag: 'https://media.api-sports.io/football/teams/5529.png',
  F3: 'MAR',
  F3Flag: 'https://media.api-sports.io/football/teams/31.png',
  F4: 'CRO',
  F4Flag: 'https://media.api-sports.io/football/teams/3.png',

  G1: 'BRA',
  G1Flag: 'BRA',
  G2: 'SRB',
  G2Flag: 'SRB',
  G3: 'SUI',
  G3Flag: 'https://media.api-sports.io/football/teams/15.png',
  G4: 'CMR',
  G4Flag: 'https://media.api-sports.io/football/teams/1530.png',

  H1: 'POR',
  H1Flag: 'https://media.api-sports.io/football/teams/27.png',
  H2: 'GHA',
  H2Flag: 'https://media.api-sports.io/football/teams/1504.png',
  H3: 'URU',
  H3Flag: 'https://media.api-sports.io/football/teams/7.png',
  H4: 'KOR',
  H4Flag: 'https://media.api-sports.io/football/teams/17.png',

  TIE: 'TIE',
}
